import { salon } from '../data/salonData'
import { ArrowUpRight, InstagramIcon, MenuIcon, PhoneIcon, WhatsAppIcon } from './Icons'
import { SectionHeading } from './SectionHeading'

export function Header({ menuOpen, setMenuOpen, navigation }) { return <header className="site-header"><a className="brand" href="#top" aria-label={`${salon.name} home`}><span>{salon.shortName}</span><small>MEN'S SALON</small></a><nav className={menuOpen ? 'nav nav--open' : 'nav'} aria-label="Primary navigation">{navigation.map((item) => <a href={item.href} key={item.href} onClick={() => setMenuOpen(false)}>{item.label}</a>)}<a className="nav__booking" href={salon.bookingHref}>Book a chair <ArrowUpRight size={15} /></a></nav><button className="menu-button" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><MenuIcon open={menuOpen} /></button></header> }
export function Hero() { return <section className="hero" id="top"><img src={salon.heroImage} alt="Barber shaping a modern men's haircut" /><div className="hero__shade" /><div className="hero__content page-shell"><p className="eyebrow eyebrow--light">Est. 2016 - Bandra, Mumbai</p><h1>Good hair.<br /><em>Good energy.</em></h1><p className="hero__description">{salon.description}</p><div className="hero__actions"><a className="button button--gold" href={salon.bookingHref}>Book an appointment <ArrowUpRight size={16} /></a><a className="text-link text-link--light" href="#services">Explore services <span>down</span></a></div></div><div className="hero__stamp" aria-hidden="true"><span>27</span><small>Cut - Care - Craft</small></div></section> }
export function About() { return <section className="section about" id="about"><div className="page-shell about__grid"><div className="about__image-wrap"><img src={salon.aboutImage} alt="Interior of 27 Men's Salon" /><span className="image-label">Inside 27 / 01</span></div><div className="about__copy"><SectionHeading eyebrow="The 27 standard" title="A better kind of grooming." text="We believe the best style is the one that feels like you. Our space is built around unhurried consultations, excellent craft, and the small rituals that turn a regular cut into a proper reset." /><div className="stat-row"><div><strong>08</strong><span>Years of craft</span></div><div><strong>12k+</strong><span>Happy guests</span></div><div><strong>04</strong><span>Master stylists</span></div></div><a className="text-link" href="#contact">More about our story <ArrowUpRight size={16} /></a></div></div></section> }
export function Services() { return <section className="section services" id="services"><div className="page-shell"><SectionHeading eyebrow="What we do" title="The chair is yours." text="Thoughtful services, tailored to your face, your hair, and your day." /><div className="service-list">{salon.services.map((service) => <article className="service-item" key={service.number}><span className="service-item__number">{service.number}</span><div><h3>{service.name}</h3><p>{service.detail}</p></div><strong>{service.price}</strong><ArrowUpRight size={20} /></article>)}</div></div></section> }
export function Pricing() { return <section className="section pricing"><div className="page-shell pricing__grid"><SectionHeading eyebrow="Straightforward pricing" title="Your ritual, your way." text="Come in for the essential, stay for the experience." /><div className="price-table">{salon.pricing.map((item) => <div className="price-row" key={item.name}><div><h3>{item.name}</h3><p>{item.detail}</p></div><strong>{item.price}</strong></div>)}<a className="text-link" href={salon.bookingHref}>View full menu <ArrowUpRight size={16} /></a></div></div></section> }
export function WhyUs() { const points = ['Personal consultation, every time', 'A calm space with zero rush', 'Only the best tools & products', 'A style that works beyond the chair']; return <section className="dark-section why"><div className="page-shell why__grid"><SectionHeading light eyebrow="Why 27" title="The difference is in the details." /><div className="why__list">{points.map((point, i) => <div key={point}><span>0{i + 1}</span><p>{point}</p></div>)}</div></div></section> }
export function Gallery() { return <section className="section gallery" id="gallery"><div className="page-shell"><SectionHeading eyebrow="The space" title="Come for the cut. Stay for the feeling." /><div className="gallery__grid">{salon.gallery.map((image, index) => <img key={image} src={image} alt={`27 Men's Salon detail ${index + 1}`} />)}</div></div></section> }
export function Team() { return <section className="section team"><div className="page-shell"><SectionHeading eyebrow="The people behind the craft" title="Meet your new regulars." /><div className="team__grid">{salon.team.map((member) => <article className="team-card" key={member.name}><div className="team-card__image"><img src={member.image} alt={member.name} /></div><h3>{member.name}</h3><p>{member.role}</p></article>)}</div></div></section> }
export function Testimonials() { return <section className="section testimonials"><div className="page-shell"><div className="testimonials__intro"><SectionHeading eyebrow="Good words" title="Leave looking sharp. Feel even better." /><span className="quote-mark">&quot;</span></div><div className="testimonial-grid">{salon.testimonials.map((item) => <blockquote key={item.name}><div className="stars">*****</div><p>&quot;{item.quote}&quot;</p><footer><strong>{item.name}</strong><span>{item.meta}</span></footer></blockquote>)}</div></div></section> }
export function Offer() { return <section className="offer"><div className="page-shell offer__inner"><div><p className="eyebrow">A little something extra</p><h2>First time at 27?</h2><p>Enjoy 15% off your first Signature Cut. Consider it a proper introduction.</p></div><a className="button button--dark" href={salon.bookingHref}>Claim your welcome <ArrowUpRight size={16} /></a></div></section> }
export function Appointment() { return <section className="dark-section appointment" id="appointment"><div className="page-shell appointment__inner"><SectionHeading light eyebrow="Your chair is waiting" title="Make time for yourself." text="Book online in under a minute, or give us a call. We will take it from there." /><a className="button button--gold" href={salon.whatsappHref} target="_blank" rel="noreferrer">Book on WhatsApp <WhatsAppIcon /></a></div></section> }
export function Contact() { return <section className="section contact" id="contact"><div className="page-shell contact__grid"><div><SectionHeading eyebrow="Find your way to us" title="See you at 27." /><div className="contact__details"><a href={salon.phoneHref}><PhoneIcon /><span><small>Call us</small>{salon.phone}</span></a><a href={salon.mapHref} target="_blank" rel="noreferrer"><span><small>Visit us</small>{salon.address}</span><ArrowUpRight size={16} /></a><div><span><small>Opening hours</small>{salon.hours}</span></div></div><a className="button button--dark" href={salon.mapHref} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={16} /></a></div><div className="map-placeholder"><div className="map-placeholder__pin">27</div><p>Linking Road<br /><span>Bandra West, Mumbai</span></p><a href={salon.mapHref} target="_blank" rel="noreferrer">Open in Maps <ArrowUpRight size={14} /></a></div></div></section> }
export function Footer() { return <footer className="footer"><div className="page-shell footer__top"><a className="brand brand--footer" href="#top"><span>{salon.shortName}</span><small>MEN'S SALON</small></a><div><p>{salon.tagline}</p><a className="text-link text-link--light" href={salon.bookingHref}>Book your chair <ArrowUpRight size={15} /></a></div><div className="footer__social"><a href={salon.instagramHref} target="_blank" rel="noreferrer" aria-label="Instagram"><InstagramIcon /></a><a href={salon.whatsappHref} target="_blank" rel="noreferrer" aria-label="WhatsApp"><WhatsAppIcon /></a><a href={salon.phoneHref} aria-label="Call us"><PhoneIcon /></a></div></div><div className="page-shell footer__bottom"><span>Copyright 2025 {salon.name}</span><span>Made for good hair days.</span></div></footer> }